<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="tasks\eod_report\scripts\getReportData.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="tasks\eod_report\scripts\getReportData.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\webscrapper.plugins.common\webscrapper.plugins.common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="tasks\authentication\scripts\" />
  </ItemGroup>

</Project>
